disabled_rules:
  - identifier_name
  - trailing_comma
  - type_name

line_length:
  - 300 # warning
  - 300 # error

function_body_length:
  - 200 # warning
  - 200 # error

cyclomatic_complexity:
  - 50 # warning
  - 50 # error

function_parameter_count:
  - 10 # warning
  - 10 # error